title: DKR
author: Dirk Verreyen
email: verreyen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Grafische projecten

# social links
github_username:  dirkverreyen # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
